import type { ProductCategory, ProductOption } from './supabase';

export interface MenuItem {
  id: string;
  name: string;
  category: ProductCategory | string;
  price: string;
  description: string;
  tag?: string;
  isSpecialty?: boolean;
  options?: ProductOption[] | string[];
}

export interface ReservationData {
  service: string;
  date: string;
  time: string;
  guests: number;
  name: string;
  phone: string;
  email: string;
  notes?: string;
}

export const MENU_ITEMS: MenuItem[] = [
  // ========================================================
  // CATEGORIE 1 : PETIT-DÉJEUNER
  // ========================================================
  {
    id: 'pd-1',
    name: 'Petit déjeuner Simple',
    category: 'petit-dejeuner',
    price: '3 000 FCFA',
    description: 'Café, thé, chocolat ou lait chaud accompagné de pain frais croustillant, beurre fin et assortiment de confitures.',
    tag: 'Matin Douceur',
  },
  {
    id: 'pd-2',
    name: 'Petit déjeuner Amélioré',
    category: 'petit-dejeuner',
    price: '4 500 FCFA',
    description: 'Café, thé, chocolat ou lait chaud, 2 viennoiseries pur beurre dorées au four et verre de jus de fruits frais nature.',
    tag: 'Classique',
  },
  {
    id: 'pd-3',
    name: 'Petit déjeuner Times',
    category: 'petit-dejeuner',
    price: '6 000 FCFA',
    description: 'Café, thé, chocolat ou lait chaud, sucre ou miel pur, viennoiseries maison, omelette nature baveuse et jus frais pressé.',
    tag: 'Signature Matin',
    isSpecialty: true,
  },
  {
    id: 'pd-4',
    name: 'Petit déjeuner Composé',
    category: 'petit-dejeuner',
    price: '8 000 FCFA',
    description: 'Boisson chaude au choix, sucre ou miel, corbeille de viennoiseries, omelette garnie jambon-fromage ou aux légumes croquants et grand jus de fruits frais.',
    tag: 'Prestige Gourmand',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 2 : ENTRÉES & SALADES
  // ========================================================
  {
    id: 'es-1',
    name: 'Salade Fattouche',
    category: 'entrees-salades',
    price: '5 000 FCFA',
    description: 'Laitue croquante, tomate fraîche, concombre, oignon vert, poivron doux, menthe, persil plat, sumak acidulé, pain pita grillé et mélasse de grenade.',
    tag: 'Saveurs du Levant',
  },
  {
    id: 'es-2',
    name: 'Salade Tabouleh',
    category: 'entrees-salades',
    price: '5 000 FCFA',
    description: 'Semoule de blé fine, persil frais ciselé, poivron, tomate mûre, menthe fraîche, oignon vert, échalote, pur jus de citron et huile d’olive extra vierge.',
    tag: 'Fraîcheur',
  },
  {
    id: 'es-3',
    name: 'Salade César',
    category: 'entrees-salades',
    price: '6 000 FCFA',
    description: 'Cœur de romaine, escalope de poulet grillé minute aux braises, lardons fumés dorés, copeaux de parmesan affiné et croûtons dorés à l’ail.',
    tag: 'Best-Seller',
    isSpecialty: true,
  },
  {
    id: 'es-4',
    name: 'Salade Grecque',
    category: 'entrees-salades',
    price: '6 000 FCFA',
    description: 'Laitue, tomates gorgées de soleil, oignon rouge, concombre croquant, véritable feta grecque AOP, menthe fraîche, olives noires de Kalamata et origan.',
  },
  {
    id: 'es-5',
    name: 'Salade Niçoise',
    category: 'entrees-salades',
    price: '6 000 FCFA',
    description: 'Laitue, tomates fraîches, haricots verts fins, filets d’anchois, pommes de terre fondantes, thon émietté, œuf dur fermier, oignons et olives noires.',
  },
  {
    id: 'es-6',
    name: 'Salade du Chef',
    category: 'entrees-salades',
    price: '6 500 FCFA',
    description: 'Laitue, maïs doux, carottes râpées, lamelles de gruyère suisse, tomate, oignon, œuf dur, émincé de poulet fermier, jambon supérieur et haricots verts.',
    tag: 'Gourmande',
  },
  {
    id: 'es-7',
    name: 'Salade Mexicana au poulet',
    category: 'entrees-salades',
    price: '6 500 FCFA',
    description: 'Laitue, dés de tomates, gruyère, surimi, avocat fondant, escalope de poulet grillé aux épices fajitas, haricots rouges, maïs et chips tortilla croquantes.',
    tag: 'Épicée & Croquante',
  },
  {
    id: 'es-8',
    name: 'Hors d’œuvre Chaude',
    category: 'entrees-salades',
    price: '7 000 FCFA',
    description: 'Pommes de terre fondantes, carottes glacées, haricots verts sautés, émincé de blanc de poulet tendre et sauce veloutée à la crème fraîche.',
  },
  {
    id: 'es-9',
    name: 'Petits pois à la viande aux pommes de terre',
    category: 'entrees-salades',
    price: '7 000 FCFA',
    description: 'Petits pois doux mijotés avec morceaux de viande fondante et dés de pommes de terre rissolées dans un jus réduit aromatique.',
  },
  {
    id: 'es-10',
    name: 'Salade Times',
    category: 'entrees-salades',
    price: '7 000 FCFA',
    description: 'Laitue, tomates fraîches, jambon supérieur, avocat hass, escalope de poulet fermier grillé à la flamme et croûtons croustillants gratinés au fromage.',
    tag: 'Signature Maison',
    isSpecialty: true,
  },
  {
    id: 'es-11',
    name: 'Salade d’Avocat aux crevettes',
    category: 'entrees-salades',
    price: '7 000 FCFA',
    description: 'Cœur de laitue, avocat tropical fondant, belles crevettes sauvages fraîches pochées et sauce cocktail maison subtilement relevée.',
    tag: 'Fraîcheur Marine',
  },
  {
    id: 'es-12',
    name: 'Vermicelle Chinoise aux œufs de caille',
    category: 'entrees-salades',
    price: '7 000 FCFA',
    description: 'Vermicelles de soja translucides sautées au wok, œufs de caille mollets, petits légumes croquants et sauce soja parfumée au sésame grillé.',
  },
  {
    id: 'es-13',
    name: 'Hors d’œuvre Times',
    category: 'entrees-salades',
    price: '8 000 FCFA',
    description: 'Pommes de terre fondantes, carottes primeurs, haricots verts, boulettes de viande parfumées maison, petits pois, crème fraîche onctueuse et chiffonnade de jambon.',
    tag: 'Généreux',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 3 : SOUPES & POTAGES
  // ========================================================
  {
    id: 'sp-1',
    name: 'Gaspacho',
    category: 'soupes-potages',
    price: '6 000 FCFA',
    description: 'Soupe froide andalouse de tomates fraîches, poivrons rouges, concombres, ail doux, huile d’olive extra vierge et vinaigre de Xérès.',
    tag: 'Fraîcheur d’Été',
  },
  {
    id: 'sp-2',
    name: 'Minestrone',
    category: 'soupes-potages',
    price: '6 000 FCFA',
    description: 'Célèbre soupe paysanne italienne mijotée aux légumes du marché, haricots blancs, petites pâtes fraîches, herbes aromatiques et parmesan.',
  },
  {
    id: 'sp-3',
    name: 'Potage de poulet',
    category: 'soupes-potages',
    price: '6 000 FCFA',
    description: 'Velouté réconfortant et onctueux au blanc de volaille mijoté, petits légumes racines et trait de crème fraîche.',
    tag: 'Réconfortant',
  },
  {
    id: 'sp-4',
    name: 'Soupe de pêcheur',
    category: 'soupes-potages',
    price: '7 000 FCFA',
    description: 'Bouillon marin corsé préparé avec les poissons du jour, crevettes fraîches et fruits de mer, relevé d’aromates et de safran.',
    tag: 'Saveur Océane',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 4 : PIZZAS (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'pz-1',
    name: 'Pizza Margherita',
    category: 'pizzas',
    price: '5 500 FCFA',
    description: 'Pâte fine artisanale, sauce tomate mijotée à l’origan, mozzarella fior di latte fondante et basilic frais.',
    tag: 'Classique Italienne',
  },
  {
    id: 'pz-2',
    name: 'Pizza Bourguignonne',
    category: 'pizzas',
    price: '6 500 FCFA',
    description: 'Sauce tomate, mozzarella onctueuse, lamelles de bœuf tendre mariné, poivrons grillés et olives noires.',
  },
  {
    id: 'pz-3',
    name: 'Pizza Végétario',
    category: 'pizzas',
    price: '6 500 FCFA',
    description: 'Sauce tomate, mozzarella fondante, poivrons multicolores, oignons doux, basilic frais et grains de maïs doré.',
    tag: 'Végétarien',
  },
  {
    id: 'pz-4',
    name: 'Pizza du Chef',
    category: 'pizzas',
    price: '6 500 FCFA',
    description: 'Sauce tomate maison, mozzarella, émincé de poulet rôti, crème fraîche onctueuse, champignons de Paris frais et olives.',
    tag: 'Coup de Cœur',
  },
  {
    id: 'pz-5',
    name: 'Pizza Milano',
    category: 'pizzas',
    price: '6 500 FCFA',
    description: 'Sauce tomate mijotée, mozzarella fondante, thon émietté de premier choix et olives noires à la grecque.',
  },
  {
    id: 'pz-6',
    name: 'Pizza 4 Saisons',
    category: 'pizzas',
    price: '6 500 FCFA',
    description: 'Sauce tomate, mozzarella, jambon blanc supérieur, cœurs d’artichauts marinés, champignons frais et olives noires.',
  },
  {
    id: 'pz-7',
    name: 'Pizza 4 Fromages',
    category: 'pizzas',
    price: '6 500 FCFA',
    description: 'Sauce tomate mijotée, alliance généreuse de mozzarella fondante, gruyère affiné, parmesan reggiano et roquefort crémeux.',
    tag: 'Pour les Amateurs',
  },
  {
    id: 'pz-8',
    name: 'Pizza Times',
    category: 'pizzas',
    price: '7 000 FCFA',
    description: 'Sauce crémeuse signature, poulet rôti, viande hachée assaisonnée, poivrons croquants, oignons dorés, olives et mozzarella gratinée.',
    tag: 'Signature Pizza',
    isSpecialty: true,
  },
  {
    id: 'pz-9',
    name: 'Pizza Pépéroni',
    category: 'pizzas',
    price: '7 000 FCFA',
    description: 'Sauce tomate relevée, généreuse couche de mozzarella fondante et tranches de chorizo pépéroni espagnol grillé et croustillant.',
  },
  {
    id: 'pz-10',
    name: 'Pizza Océano',
    category: 'pizzas',
    price: '7 500 FCFA',
    description: 'Sauce tomate parfumée, sélection de fruits de mer (crevettes, calamars, moules), ail, persil plat et mozzarella gratinée.',
    tag: 'Fruits de Mer',
    isSpecialty: true,
  },
  {
    id: 'pz-11',
    name: 'Pizza Reine',
    category: 'pizzas',
    price: '7 500 FCFA',
    description: 'Sauce tomate, mozzarella fondante, jambon de qualité supérieure, poivrons rouges, champignons de Paris frais et olives noires.',
    tag: 'Incontournable',
  },

  // ========================================================
  // CATEGORIE 5 : PASTAS (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'pa-1',
    name: 'Penne Arabiata',
    category: 'pastas',
    price: '6 000 FCFA',
    description: 'Penne al dente enrobées d’une sauce tomate mijotée pimentée, poivrons doux revenus à l’huile d’olive et basilic frais.',
    tag: 'Piquant & Savoureux',
  },
  {
    id: 'pa-2',
    name: 'Spaghetti Carbonara',
    category: 'pastas',
    price: '7 000 FCFA',
    description: 'Spaghetti al dente, jaunes d’œufs battus, crème fraîche légère, bacon croustillant, dés de jambon et parmesan affiné.',
    tag: 'Classique Italien',
    isSpecialty: true,
  },
  {
    id: 'pa-3',
    name: 'Spaghetti Bolognaise',
    category: 'pastas',
    price: '7 000 FCFA',
    description: 'Sauce tomate mijotée de longues heures avec viande de bœuf hachée sélectionnée, mirepoix de carottes et oignons, pointe de vin rouge et herbes.',
  },
  {
    id: 'pa-4',
    name: 'Tagliatelle aux fruits de mer',
    category: 'pastas',
    price: '7 000 FCFA',
    description: 'Tagliatelles fraîches, crevettes, calamars et moules liés dans une sauce onctueuse associant pulpe de tomate et crème fraîche parfumée à l’ail.',
    tag: 'Saveurs Marines',
    isSpecialty: true,
  },
  {
    id: 'pa-5',
    name: 'Tagliatelle gambas chorizo',
    category: 'pastas',
    price: '7 500 FCFA',
    description: 'Tagliatelles fraîches, belles gambas poêlées au beurre blanc, tranches de chorizo ibérique grillé et coulis de tomates cerises au piment doux.',
    tag: 'Terre & Mer',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 6 : BURGERS & SANDWICHS (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'bs-1',
    name: 'Croque Monsieur',
    category: 'burgers-sandwichs',
    price: '5 000 FCFA',
    description: 'Pain de mie artisanal beurré et toasté minute, jambon supérieur, béchamel muscade onctueuse et fromage gratiné doré au four.',
  },
  {
    id: 'bs-2',
    name: 'Croque Madame',
    category: 'burgers-sandwichs',
    price: '5 500 FCFA',
    description: 'Notre traditionnel croque-monsieur gratiné surmonté d’un œuf au plat fermier au jaune coulant.',
  },
  {
    id: 'bs-3',
    name: 'Chiken Burger',
    category: 'burgers-sandwichs',
    price: '5 500 FCFA',
    description: 'Filet de poulet croustillant mariné, pain brioché toasté, laitue fraîche, tomates mûres, oignons rouges et sauce burger maison crémeuse.',
    tag: 'Best-Seller Poulet',
  },
  {
    id: 'bs-4',
    name: 'Sandwich Végétarien au fromage',
    category: 'burgers-sandwichs',
    price: '5 500 FCFA',
    description: 'Baguette fraîche croustillante, assortiment de crudités du marché, tranches de fromage fondant et mayonnaise légère aux herbes.',
    tag: 'Végétarien',
  },
  {
    id: 'bs-5',
    name: 'Sandwich au Poulet',
    category: 'burgers-sandwichs',
    price: '5 500 FCFA',
    description: 'Pain baguette croustillant garni d’émincé de blanc de poulet sauté minute aux herbes, feuilles de laitue et tomates.',
  },
  {
    id: 'bs-6',
    name: 'Sandwich à la Viande',
    category: 'burgers-sandwichs',
    price: '5 500 FCFA',
    description: 'Lamelles de bœuf tendre marinées et saisies à feu vif, oignons caramélisés et moutarde douce dans un pain artisanal frais.',
  },
  {
    id: 'bs-7',
    name: 'Hamburger',
    category: 'burgers-sandwichs',
    price: '6 000 FCFA',
    description: 'Steak haché de bœuf pur jus 150g grillé à la commande, cornichons doux, oignons rouges, rondelles de tomate, laitue et sauce barbecue maison.',
  },
  {
    id: 'bs-8',
    name: 'Végétarien Cheese Burger',
    category: 'burgers-sandwichs',
    price: '6 000 FCFA',
    description: 'Steak végétal savoureux grillé, double tranche de cheddar fondant, légumes frais croquants et sauce relish maison.',
    tag: 'Végétarien',
  },
  {
    id: 'bs-9',
    name: 'Panini au Poulet',
    category: 'burgers-sandwichs',
    price: '6 000 FCFA',
    description: 'Pain ciabatta pressé à chaud, poulet mariné aux herbes de Provence, mozzarella fondante et filet d’huile d’olive.',
  },
  {
    id: 'bs-10',
    name: 'Sandwich au Jambon',
    category: 'burgers-sandwichs',
    price: '6 500 FCFA',
    description: 'Baguette croustillante, beurre frais de baratte, tranches généreuses de jambon blanc supérieur, emmental et cornichons.',
  },
  {
    id: 'bs-11',
    name: 'Club Sandwich',
    category: 'burgers-sandwichs',
    price: '6 500 FCFA',
    description: 'Pain de mie toasté à trois étages, escalope de poulet grillé, bacon croustillant, œuf dur, tomate, laitue et mayonnaise, servi avec frites dorées.',
    tag: 'Classique Brasserie',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 7 : SPÉCIALITÉS LIBANAISES (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'lb-1',
    name: 'Houmoss',
    category: 'specialites-libanaises',
    price: '4 500 FCFA',
    description: 'Onctueuse purée de pois chiches à la crème de sésame (tahini), jus de citron frais pressé, ail doux et filet d’huile d’olive extra vierge.',
    tag: 'Mezzé Végétarien',
  },
  {
    id: 'lb-2',
    name: 'Houmoss à la viande',
    category: 'specialites-libanaises',
    price: '5 500 FCFA',
    description: 'Houmoss traditionnel et velouté garni d’émincé de filet de bœuf poêlé aux épices orientales et pignons de pin torréfiés.',
    tag: 'Spécialité Maison',
    isSpecialty: true,
  },
  {
    id: 'lb-3',
    name: 'Sambousek légumes',
    category: 'specialites-libanaises',
    price: '5 500 FCFA',
    description: 'Délicieux petits chaussons feuilletés croustillants farcis d’un mélange de légumes primeurs parfumés à la coriandre et au sumak.',
  },
  {
    id: 'lb-4',
    name: 'Sambousek viande',
    category: 'specialites-libanaises',
    price: '5 500 FCFA',
    description: 'Chaussons dorés et croustillants farcis à la viande hachée pur bœuf parfumée aux sept épices libanaises et pignons.',
  },
  {
    id: 'lb-5',
    name: 'Falafel assiette',
    category: 'specialites-libanaises',
    price: '5 500 FCFA',
    description: 'Boulettes dorées de pois chiches et fèves pilées aux herbes fraîches, servies avec sauce tarator au sésame, pickles et crudités.',
    tag: '100% Végétal',
  },
  {
    id: 'lb-6',
    name: 'Kafta assiette',
    category: 'specialites-libanaises',
    price: '5 500 FCFA',
    description: 'Brochettes de viande de bœuf hachée assaisonnée de persil frais, oignons doux et épices d’Orient, grillées à la braise.',
    tag: 'Grillade d’Orient',
  },
  {
    id: 'lb-7',
    name: 'Chawarma assiette',
    category: 'specialites-libanaises',
    price: '5 500 FCFA',
    description: 'Émincé de viande tendre marinée aux épices libanaises authentiques et rôtie à la broche, servie avec pain libanais et sauce à l’ail toum.',
    tag: 'Incontournable',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 8 : VIANDES ROUGES (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'vr-1',
    name: 'Brochette de boeuf (sauce au choix)',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Morceaux choisis de bœuf tendre marinés aux aromates puis saisis à la flamme vive sur braises de bois, avec sauce au poivre, roquefort ou champignons.',
    tag: 'Grillade Braisée',
  },
  {
    id: 'vr-2',
    name: 'Boulette de viande (sauce au choix)',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Généreuses boulettes de bœuf haché maison cuisinées minute, nappées de votre sauce préférée (sauce tomate mijotée, poivre vert ou crème fraîche).',
  },
  {
    id: 'vr-3',
    name: 'Côte d’agneau grillé',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Côtes d’agneau premières grillées sur feu de bois, parfumées au romarin frais, fleur de sel et ail en chemise.',
    tag: 'Tendre & Savoureux',
  },
  {
    id: 'vr-4',
    name: 'Côte de boeuf au beurre maître d’hôtel',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Belle pièce de bœuf persillée saisie à très haute température, surmontée d’un médaillon de beurre de baratte persillé au jus de citron.',
    tag: 'Sélection Bouchère',
    isSpecialty: true,
  },
  {
    id: 'vr-5',
    name: 'Filet de boeuf sauce aurore',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Cœur de filet de bœuf d’une tendreté exceptionnelle nappé d’une sauce aurore veloutée alliant crème fraîche et réduction de tomate fraîche.',
  },
  {
    id: 'vr-6',
    name: 'Filet de boeuf poivron vert',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Filet de bœuf poêlé selon votre cuisson désirée, accompagné d’une réduction parfumée aux poivrons verts doux caramélisés.',
  },
  {
    id: 'vr-7',
    name: 'Filet de boeuf à la sauce crème et champignon',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Cœur de filet tendre et juteux nappé d’une onctueuse sauce forestière aux champignons de Paris frais et crème double.',
    tag: 'Best-Seller Viande',
    isSpecialty: true,
  },
  {
    id: 'vr-8',
    name: 'Mignonne de boeuf au poivre vert',
    category: 'viandes-rouges',
    price: '8 000 FCFA',
    description: 'Médaillon de filet mignon de bœuf saisi minute et flambé, servi avec une sauce au poivre vert frais de Madagascar liée au cognac.',
    tag: 'Signature Chef',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 9 : POULETS (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'po-1',
    name: 'Aile de poulet pané',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Ailes de volaille fraîches marinées aux épices douces et enrobées d’une chapelure dorée extra croustillante.',
  },
  {
    id: 'po-2',
    name: 'Brochette de poulet grillé',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Blancs de poulet fermier découpés en gros cubes, marinés au citron vert et thym sauvage, grillés au barbecue.',
    tag: 'Léger & Grillé',
  },
  {
    id: 'po-3',
    name: 'Croquette de poulet',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Bouchées fondantes de poulet haché assaisonné d’aromates fins, panées et frites à point, servies avec sauce dip.',
  },
  {
    id: 'po-4',
    name: 'Demi-poulet grillé',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Demi-poulet mariné pendant 12 heures dans notre mélange d’épices locales et grillé lentement sur braises ardentes.',
    tag: 'Spécialité Rôtisserie',
    isSpecialty: true,
  },
  {
    id: 'po-5',
    name: 'Escalope de poulet à la sauce crème et moutarde',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Escalope de volaille saisie au beurre puis mijotée dans une sauce veloutée à la crème fraîche et moutarde à l’ancienne.',
  },
  {
    id: 'po-6',
    name: 'Escalope de poulet à la sauce crème et champignon',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Tendre escalope de poulet dorée minute, nappée d’une crème onctueuse aux lamelles de champignons de Paris frais.',
    tag: 'Coup de Cœur',
  },
  {
    id: 'po-7',
    name: 'Nuggets de poulet',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Vrais filets de poulet découpés et panés minute, moelleux à cœur et croustillants à l’extérieur.',
  },
  {
    id: 'po-8',
    name: 'Poulet strogonoff',
    category: 'poulets',
    price: '7 500 FCFA',
    description: 'Aiguillettes de poulet revenues avec champignons, oignons fondants, crème acidulée, pointe de paprika doux et moutarde.',
    tag: 'Gourmand',
  },

  // ========================================================
  // CATEGORIE 10 : POISSONS ET CRUSTACÉS (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'pc-1',
    name: 'Brochettes de Poisson',
    category: 'poissons-crustaces',
    price: '8 000 FCFA',
    description: 'Dés de mérou et lotte fraîchement pêchés marinés au citron vert et herbes fraîches, embrochés et saisis aux braises.',
    tag: 'Pêche du Jour',
  },
  {
    id: 'pc-2',
    name: 'Sole meunière',
    category: 'poissons-crustaces',
    price: '8 000 FCFA',
    description: 'Belle sole entière farinée et dorée doucement au beurre clarifié, servie avec jus de citron pressé et persil plat frais.',
    tag: 'Classique Gastronomique',
  },
  {
    id: 'pc-3',
    name: 'Sole normande (filet de sole, crevette, champignon)',
    category: 'poissons-crustaces',
    price: '8 000 FCFA',
    description: 'Filets de sole pochés nappés d’une réduction crémée liée aux crevettes décortiquées et champignons sautés au beurre.',
    tag: 'Raffiné',
    isSpecialty: true,
  },
  {
    id: 'pc-4',
    name: 'Filet de poisson à la sauce crème et champignon',
    category: 'poissons-crustaces',
    price: '8 000 FCFA',
    description: 'Filet de poisson noble poêlé au beurre fin et nappé d’une émulsion crémeuse forestière aux champignons.',
  },
  {
    id: 'pc-5',
    name: 'Crevettes provençales',
    category: 'poissons-crustaces',
    price: '8 000 FCFA',
    description: 'Crevettes fraîches sautées à l’huile d’olive vierge avec tomates concassées, ail doux, persil et herbes de Provence.',
  },
  {
    id: 'pc-6',
    name: 'Curry de poisson et crevette',
    category: 'poissons-crustaces',
    price: '8 500 FCFA',
    description: 'Morceaux de poisson et crevettes entières mijotés dans une sauce onctueuse au curry madras et lait de coco crémeux.',
    tag: 'Épicé & Parfumé',
  },
  {
    id: 'pc-7',
    name: 'Duo de poisson et crevette à la sauce aurore',
    category: 'poissons-crustaces',
    price: '8 500 FCFA',
    description: 'Harmonieux mariage de poisson du large et crevettes royales liés par une sauce crémeuse tomatée au vin blanc.',
  },
  {
    id: 'pc-8',
    name: 'Gambas sauté à l’ail',
    category: 'poissons-crustaces',
    price: '12 000 FCFA',
    description: 'Belles gambas royales saisies vivement à la plancha avec beurre à l’ail frais, piment doux et persil ciselé.',
    tag: 'Prestige de la Mer',
    isSpecialty: true,
  },
  {
    id: 'pc-9',
    name: 'Brochettes de gambas',
    category: 'poissons-crustaces',
    price: '12 000 FCFA',
    description: 'Gambas marinées aux zestes d’agrumes et gingembre, enfilées en brochettes et grillées au barbecue.',
    tag: 'Grillade d’Exception',
  },
  {
    id: 'pc-10',
    name: 'Langouste grillée',
    category: 'poissons-crustaces',
    price: '13 000 FCFA',
    description: 'Langouste fraîche entière coupée en deux, grillée à la flamme avec beurre maître d’hôtel fondu et citron vert.',
    tag: 'Signature Prestige',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 11 : SPÉCIALITÉS AFRICAINES (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'af-1',
    name: 'Mangnignan de kamè',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Traditionnelle sauce béninoise aux feuilles de kamè (tchayo, amanvivè), poisson fumé ou viande tendre, afitin et huile rouge.',
    tag: 'Terroir Béninois',
    isSpecialty: true,
  },
  {
    id: 'af-2',
    name: 'Monyo de kamè',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Condiments frais pilonnés en sauce monyo avec réduction de kamè parfumée au piment doux et oignons verts.',
  },
  {
    id: 'af-3',
    name: 'Monyo poisson (fumé, frite, braisé)',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Sauce monyo acidulée et relevée aux tomates fraîches et oignons, servie avec poisson préparé à votre convenance (fumé, frit ou braisé).',
    tag: 'Authentique',
  },
  {
    id: 'af-4',
    name: 'Blôkôto',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Mijoté traditionnel riche et gélatineux aux pattes de bœuf fondantes longuement mijotées avec épices locales.',
    tag: 'Spécialité Locale',
  },
  {
    id: 'af-5',
    name: 'Brochettes de gésier',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Gésiers de volaille attendris, marinés aux épices de braise et grillés au feu de bois avec oignons et piments.',
  },
  {
    id: 'af-6',
    name: 'Brochettes de wagachi ou sauté',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Authentique fromage peul traditionnel wagashi doré à l’huile parfumée ou grillé en brochettes aux herbes.',
    tag: 'Fromage Peul',
  },
  {
    id: 'af-7',
    name: 'Brochettes d’escargot',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Escargots géants d’Afrique délicatement nettoyés, marinés dans une pâte d’épices et grillés au charbon.',
    tag: 'Délice Exotique',
  },
  {
    id: 'af-8',
    name: 'Friture d’escargot au crincrin',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Escargots dorés dans une friture d’oignons et tomates, accompagnés d’une sauce crincrin aux feuilles gluantes fraîches.',
  },
  {
    id: 'af-9',
    name: 'Gbôta',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Mijoté traditionnel très réputé de tête de mouton ou de porc cuite à point jusqu’à parfaite tendreté.',
  },
  {
    id: 'af-10',
    name: 'Kedjenou',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Ragoût traditionnel mijoté à l’étouffée sans eau ajoutée avec poulet fermier, tomates fraîches, oignons, ail et piments.',
    tag: 'Spécialité Ivoirienne',
  },
  {
    id: 'af-11',
    name: 'Langue de boeuf braisée ou sautée',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Langue de bœuf fondante braisée aux braises ardentes ou sautée dans une sauce tomate relevée.',
  },
  {
    id: 'af-12',
    name: 'Aileron braisé',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Ailerons marinés aux épices de braise locales, grillés lentement avec peau croustillante et chair tendre.',
  },
  {
    id: 'af-13',
    name: 'Atassi au poisson fromage',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Emblématique plat béninois de riz et haricots mijotés ensemble, servi avec sauce friture dja, poisson doré et fromage wagashi croustillant.',
    tag: 'Grand Classique Bénin',
    isSpecialty: true,
  },
  {
    id: 'af-14',
    name: 'Poisson braisé à l’africaine',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Poisson entier mariné avec le kankan et les épices secrètes du chef, braisé au charbon de bois et servi avec sauce pimentée.',
    tag: 'Braise Authentique',
    isSpecialty: true,
  },
  {
    id: 'af-15',
    name: 'Poulet bicyclette',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Authentique poulet local élevé en liberté à la chair ferme et musquée, braisé au feu de bois ou mijoté en sauce.',
    tag: 'Poulet Fermier Local',
  },
  {
    id: 'af-16',
    name: 'Poulet DG',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Célèbre plat camerounais festif de poulet doré mijoté avec rondelles de bananes plantains frites, carottes, poivrons et haricots.',
    tag: 'Coup de Cœur',
    isSpecialty: true,
  },
  {
    id: 'af-17',
    name: 'Couscous royal',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Semoule fine cuite à la vapeur, assortiment de viandes tendres, légumes fondants mijotés et bouillon parfumé aux épices.',
  },
  {
    id: 'af-18',
    name: 'Dakouin',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Plat côtier traditionnel béninois à base de gari incorporé dans un bouillon savoureux de poissons frais mijotés aux tomates et piments.',
    tag: 'Spécialité Côtière',
  },
  {
    id: 'af-19',
    name: 'Tchep',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Véritable riz au gras sénégalais aux légumes généreux (chou, manioc, carotte) avec poisson noble ou viande rouge savoureuse.',
    tag: 'Spécialité Sénégalaise',
    isSpecialty: true,
  },
  {
    id: 'af-20',
    name: 'Tchachanga',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Viande découpée et grillée à la perfection selon la tradition haoussa, saupoudrée de kan-kan aux arachides torréfiées et piment.',
    tag: 'Street-Food Gourmand',
  },
  {
    id: 'af-21',
    name: 'Viande de mouton braisé',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Morceaux de mouton marinés aux épices traditionnelles et braisés jusqu’à obtenir une croûte caramélisée et un cœur fondant.',
  },
  {
    id: 'af-22',
    name: 'Viande de lapin braisé',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Morceaux de lapin fermier marinés aux herbes aromatiques et braisés sur grill chaud.',
    tag: 'Original & Raffiné',
  },
  {
    id: 'af-23',
    name: 'Yassa (poulet ou poisson)',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Compotée d’oignons caramélisés au jus de citron vert et moutarde de Dijon, nappant un poulet fermier ou poisson braisé.',
    tag: 'Saveur Acidulée',
  },
  {
    id: 'af-24',
    name: 'Amanvivè, Gboman ou Tchayo (viande ou poisson)',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Sauces traditionnelles béninoises de feuilles amères (amanvivè), d’épinards locaux (gboman) ou de basilic (tchayo) au choix avec viande ou poisson.',
  },
  {
    id: 'af-25',
    name: 'Fonman',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Sauce béninoise traditionnelle onctueuse aux feuilles de fonman mijotées à l’huile rouge avec poisson ou viande.',
  },
  {
    id: 'af-26',
    name: 'Man Tindjan',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Ragoût béninois de légumes verts et viandes mélangées longuement cuisiné aux épices locales et fromage peul.',
    tag: 'Plat de Fête',
  },
  {
    id: 'af-27',
    name: 'Sauce Arachide (poisson ou viande de mouton)',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Sauce mafé riche et veloutée à base de pâte d’arachides grillées, mijotée avec poisson ou morceaux de mouton tendre.',
    tag: 'Riche & Velouté',
  },
  {
    id: 'af-28',
    name: 'Sauce Rouge (poisson ou viande de mouton)',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Friture rouge dja aux tomates fraîches compotées, oignons et piments doux, avec garniture au choix de poisson ou mouton.',
  },
  {
    id: 'af-29',
    name: 'Sauce Assrôkouin',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Sauce traditionnelle gluante très prisée confectionnée à partir d’amandes de pomme de cannelle pilées avec poisson ou viande.',
    tag: 'Tradition Bénin',
  },
  {
    id: 'af-30',
    name: 'Crincrin au poisson ou viande et mixte / Gombo',
    category: 'specialites-africaines',
    price: '8 000 FCFA',
    description: 'Sauce gluante aux feuilles fraîches de crincrin ou gombo battu, garnie de poisson noble, viande tendre ou formule mixte.',
    tag: 'Incontournable',
  },

  // ========================================================
  // CATEGORIE 12 : SPÉCIALITÉS CHINOISES (PLATS PRINCIPAUX)
  // ========================================================
  {
    id: 'ch-1',
    name: 'Nems (végétarien, poulet, boeuf, poisson, crevettes)',
    category: 'specialites-chinoises',
    price: '6 000 FCFA',
    description: 'Rouleaux impériaux frits dorés et croustillants garniture au choix, servis avec feuilles de laitue, menthe fraîche et sauce nems maison.',
    tag: 'Entrée Asiatique',
  },
  {
    id: 'ch-2',
    name: 'Riz sauté cantonais',
    category: 'specialites-chinoises',
    price: '6 000 FCFA',
    description: 'Riz jasmin sauté au wok avec petits pois, carottes croquantes, œufs battus en lanières et dés de jambon supérieur ou volaille.',
    tag: 'Grand Classique Wok',
  },
  {
    id: 'ch-3',
    name: 'Riz sauté aux crevettes',
    category: 'specialites-chinoises',
    price: '7 500 FCFA',
    description: 'Riz sauté au wok à feu très vif avec belles crevettes fraîches, ciboule, œufs et sauce soja parfumée.',
    tag: 'Wok de la Mer',
  },
  {
    id: 'ch-4',
    name: 'Nouilles sautées au poulet',
    category: 'specialites-chinoises',
    price: '6 500 FCFA',
    description: 'Nouilles chinoises de blé sautées avec lamelles de poulet tendre, pousses de soja fraîches et légumes croquants.',
  },
  {
    id: 'ch-5',
    name: 'Nouilles sautées aux fruits de mer',
    category: 'specialites-chinoises',
    price: '7 500 FCFA',
    description: 'Nouilles sautées au wok garnies de crevettes, calamars tendres, poivrons et sauce d’huître veloutée.',
    tag: 'Savoureux Wok',
  },
  {
    id: 'ch-6',
    name: 'Poulet sauté aux champignons noirs et bambou',
    category: 'specialites-chinoises',
    price: '7 500 FCFA',
    description: 'Émincé de poulet fermier sauté au wok avec champignons parfumés shiitaké, pousses de bambou et sauce soja claire.',
  },
  {
    id: 'ch-7',
    name: 'Bœuf sauté aux oignons et poivrons',
    category: 'specialites-chinoises',
    price: '8 000 FCFA',
    description: 'Lamelles de bœuf marinées saisies à feu vif avec oignons croquants, poivrons multicolores et sauce au poivre de Sichuan.',
    tag: 'Best-Seller Wok',
  },
  {
    id: 'ch-8',
    name: 'Crevettes sautées sauce piquante',
    category: 'specialites-chinoises',
    price: '8 500 FCFA',
    description: 'Crevettes fraîches saisies au wok dans une sauce relevée au piment doux, gingembre frais et ail.',
    tag: 'Épicé & Délicat',
  },

  // ========================================================
  // CATEGORIE 13 : ACCOMPAGNEMENTS
  // ========================================================
  {
    id: 'ac-1',
    name: 'Frites de pommes de terre',
    category: 'accompagnements',
    price: '2 500 FCFA',
    description: 'Portion généreuse de frites maison dorées, croustillantes à l’extérieur et fondantes à l’intérieur.',
    tag: 'Accompagnement',
  },
  {
    id: 'ac-2',
    name: 'Alloco (bananes plantains frites)',
    category: 'accompagnements',
    price: '2 500 FCFA',
    description: 'Rondelles de bananes plantains mûres frites à point, dorées et doucement sucrées.',
    tag: 'Coup de Cœur',
  },
  {
    id: 'ac-3',
    name: 'Riz blanc parfumé',
    category: 'accompagnements',
    price: '2 000 FCFA',
    description: 'Riz jasmin de qualité supérieure cuit à la vapeur, léger et parfumé.',
  },
  {
    id: 'ac-4',
    name: 'Riz sauté aux légumes',
    category: 'accompagnements',
    price: '2 500 FCFA',
    description: 'Riz parfumé sauté à la poêle avec petits légumes de saison taillés en brunoise.',
  },
  {
    id: 'ac-5',
    name: 'Pommes sautées à l’ail et persil',
    category: 'accompagnements',
    price: '2 500 FCFA',
    description: 'Pommes de terre rissolées au beurre, ail frais pressé et persil plat du jardin.',
  },
  {
    id: 'ac-6',
    name: 'Purée de pommes de terre maison',
    category: 'accompagnements',
    price: '2 500 FCFA',
    description: 'Purée artisanale écrasée au beurre fin et lait entier, onctueuse et gourmande.',
  },
  {
    id: 'ac-7',
    name: 'Légumes sautés de saison',
    category: 'accompagnements',
    price: '2 500 FCFA',
    description: 'Poêlée de légumes croquants (courgettes, carottes, haricots verts, poivrons) à l’huile d’olive.',
    tag: 'Léger',
  },
  {
    id: 'ac-8',
    name: 'Igname frite',
    category: 'accompagnements',
    price: '2 500 FCFA',
    description: 'Bâtonnets d’igname blanche du Bénin frits, croustillants dehors et moelleux dedans.',
    tag: 'Terroir',
  },
  {
    id: 'ac-9',
    name: 'Attieké',
    category: 'accompagnements',
    price: '2 000 FCFA',
    description: 'Semoule de manioc fermentée et cuite à la vapeur, légèrement acidulée et aérée.',
  },
  {
    id: 'ac-10',
    name: 'Pain Pita ou Pain Maison',
    category: 'accompagnements',
    price: '1 000 FCFA',
    description: 'Corbeille de pain artisanal frais cuit du jour.',
  },

  // ========================================================
  // CATEGORIE 14 : DESSERTS
  // ========================================================
  {
    id: 'ds-1',
    name: 'Coupe de fruits frais de saison',
    category: 'desserts',
    price: '3 500 FCFA',
    description: 'Assortiment de fruits tropicaux frais du marché : ananas pain de sucre, pastèque juteuse, mangue et papaye.',
    tag: 'Léger & Nature',
  },
  {
    id: 'ds-2',
    name: 'Salade de fruits frais',
    category: 'desserts',
    price: '3 500 FCFA',
    description: 'Méli-mélo de fruits frais découpés en dés dans un sirop léger au jus d’orange et feuilles de menthe.',
  },
  {
    id: 'ds-3',
    name: 'Fondant au chocolat noir cœur coulant',
    category: 'desserts',
    price: '4 500 FCFA',
    description: 'Gâteau au chocolat noir 70% servi tiède, cœur intensément coulant, accompagné d’une boule de glace vanille.',
    tag: 'Gourmandise Absolue',
    isSpecialty: true,
  },
  {
    id: 'ds-4',
    name: 'Tiramisu artisanal au café',
    category: 'desserts',
    price: '4 500 FCFA',
    description: 'Véritable crème mascarpone aérée, biscuits cuillère imbibés d’espresso TIMES et poudre de cacao brut.',
    tag: 'Fait Maison',
  },
  {
    id: 'ds-5',
    name: 'Crêpe au Nutella ou confiture',
    category: 'desserts',
    price: '3 500 FCFA',
    description: 'Grande crêpe fine préparée minute, garnie généreusement au Nutella fondant ou confiture de fruits.',
  },
  {
    id: 'ds-6',
    name: 'Coupe 2 boules de glace au choix',
    category: 'desserts',
    price: '3 000 FCFA',
    description: 'Parfums disponibles : vanille de Madagascar, chocolat intense, fraise, mangue, café ou pistache.',
  },
  {
    id: 'ds-7',
    name: 'Coupe 3 boules de glace au choix',
    category: 'desserts',
    price: '4 000 FCFA',
    description: 'Trois boules de glaces artisanales au choix avec nuage de crème chantilly maison et amandes effilées.',
  },
  {
    id: 'ds-8',
    name: 'Crème brûlée à la vanille de Madagascar',
    category: 'desserts',
    price: '4 000 FCFA',
    description: 'Crème onctueuse infusée aux véritables gousses de vanille bourbon, caramélisée au sucre roux minute.',
    tag: 'Classique Brasserie',
  },
  {
    id: 'ds-9',
    name: 'Moelleux aux pommes ou tarte du chef',
    category: 'desserts',
    price: '4 000 FCFA',
    description: 'Pâtisserie artisanale du jour préparée avec des ingrédients frais de saison par notre chef pâtissier.',
  },

  // ========================================================
  // CATEGORIE 15 : BOISSONS NON ALCOOLISÉES
  // ========================================================
  {
    id: 'bna-1',
    name: 'Espresso',
    category: 'boissons-non-alcoolisees',
    price: '1 500 FCFA',
    description: 'Café court à la crema onctueuse, torréfaction artisanale et extraction soignée.',
    tag: 'Barista',
  },
  {
    id: 'bna-2',
    name: 'Double Espresso',
    category: 'boissons-non-alcoolisees',
    price: '2 500 FCFA',
    description: 'Double extraction de café intense et corsé pour faire le plein d’énergie.',
  },
  {
    id: 'bna-3',
    name: 'Café au lait / Cappuccino',
    category: 'boissons-non-alcoolisees',
    price: '2 500 FCFA',
    description: 'Espresso surmonté d’une micro-mousse de lait soyeuse et saupoudré d’une touche de cacao.',
  },
  {
    id: 'bna-4',
    name: 'Chocolat chaud maison',
    category: 'boissons-non-alcoolisees',
    price: '2 500 FCFA',
    description: 'Chocolat au lait entier crémeux et velouté préparé à l’ancienne.',
  },
  {
    id: 'bna-5',
    name: 'Thé & Infusions (menthe, vert, noir, verveine)',
    category: 'boissons-non-alcoolisees',
    price: '2 000 FCFA',
    description: 'Sélection de thés d’origine et infusions de plantes fraîches au choix.',
  },
  {
    id: 'bna-6',
    name: 'Eau minérale Possotomé 1.5L',
    category: 'boissons-non-alcoolisees',
    price: '1 500 FCFA',
    description: 'Grande bouteille d’eau minérale naturelle de source locale de Possotomé.',
  },
  {
    id: 'bna-7',
    name: 'Eau minérale Possotomé 0.5L',
    category: 'boissons-non-alcoolisees',
    price: '1 000 FCFA',
    description: 'Petite bouteille d’eau minérale naturelle servie fraîche.',
  },
  {
    id: 'bna-8',
    name: 'Eau gazeuse Perrier / San Pellegrino',
    category: 'boissons-non-alcoolisees',
    price: '2 500 FCFA',
    description: 'Eau minérale pétillante servie fraîche avec rondelle de citron vert.',
  },
  {
    id: 'bna-9',
    name: 'Sodas (Coca-Cola, Fanta, Sprite, Schweppes Tonic)',
    category: 'boissons-non-alcoolisees',
    price: '1 500 FCFA',
    description: 'Canette ou bouteille en verre 33cl servie très fraîche avec glaçons et citron.',
  },
  {
    id: 'bna-10',
    name: 'Energy Drink Red Bull',
    category: 'boissons-non-alcoolisees',
    price: '2 500 FCFA',
    description: 'Boisson énergisante servie très fraîche.',
  },
  {
    id: 'bna-11',
    name: 'Jus d’ananas frais pressé',
    category: 'boissons-non-alcoolisees',
    price: '2 500 FCFA',
    description: '100% pur jus d’ananas pain de sucre d’Allada pressé à la minute sans eau ajoutée.',
    tag: '100% Pur Jus Local',
    isSpecialty: true,
  },
  {
    id: 'bna-12',
    name: 'Jus d’orange pressée',
    category: 'boissons-non-alcoolisees',
    price: '3 000 FCFA',
    description: 'Oranges fraîches pressées à la commande pour faire le plein de vitamines.',
  },
  {
    id: 'bna-13',
    name: 'Jus de bissap maison',
    category: 'boissons-non-alcoolisees',
    price: '2 000 FCFA',
    description: 'Infusion traditionnelle de calices d’hibiscus, subtilement sucrée et parfumée à la menthe fraîche.',
    tag: 'Boisson Africaine',
  },
  {
    id: 'bna-14',
    name: 'Jus de gingembre maison',
    category: 'boissons-non-alcoolisees',
    price: '2 000 FCFA',
    description: 'Extraction tonifiante de racine de gingembre frais relevée d’une touche de citron vert et ananas.',
    tag: 'Énergisant Naturel',
  },
  {
    id: 'bna-15',
    name: 'Jus de mangue ou fruits de la passion',
    category: 'boissons-non-alcoolisees',
    price: '2 500 FCFA',
    description: 'Nectar onctueux de fruits tropicaux gorgés de soleil.',
  },
  {
    id: 'bna-16',
    name: 'Virgin Mojito',
    category: 'boissons-non-alcoolisees',
    price: '4 000 FCFA',
    description: 'Feuilles de menthe fraîche pilées, quartiers de citron vert, sirop de canne et eau gazeuse rafraîchissante.',
    tag: 'Mocktail Frais',
  },
  {
    id: 'bna-17',
    name: 'Virgin Colada',
    category: 'boissons-non-alcoolisees',
    price: '4 000 FCFA',
    description: 'Onctueuse émulsion de pur jus d’ananas et crème de noix de coco avec touche de vanille.',
  },
  {
    id: 'bna-18',
    name: 'Smoothie Tropical Mangue-Banane',
    category: 'boissons-non-alcoolisees',
    price: '4 000 FCFA',
    description: 'Fruits frais mixés minute avec yaourt nature crémeux et filet de miel pur.',
  },
  {
    id: 'bna-19',
    name: 'Cocktail Times Sunset Sans Alcool',
    category: 'boissons-non-alcoolisees',
    price: '4 500 FCFA',
    description: 'Création maison dégradée aux jus d’orange, ananas frais, purée de passion et coulis de grenadine.',
    tag: 'Création Maison',
    isSpecialty: true,
  },

  // ========================================================
  // CATEGORIE 16 : BOISSONS ALCOOLISÉES
  // ========================================================
  {
    id: 'ba-1',
    name: 'La Béninoise',
    category: 'boissons-alcoolisees',
    price: '1 500 FCFA',
    description: 'Bière blonde nationale emblématique du Bénin, rafraîchissante et légère (65cl).',
    tag: 'Bière Locale',
  },
  {
    id: 'ba-2',
    name: 'Castel Beer',
    category: 'boissons-alcoolisees',
    price: '1 500 FCFA',
    description: 'Bière blonde panafricaine désaltérante servie très fraîche (65cl).',
  },
  {
    id: 'ba-3',
    name: 'Beaufort Lager',
    category: 'boissons-alcoolisees',
    price: '2 000 FCFA',
    description: 'Bière blonde premium raffinée au goût équilibré (50cl).',
  },
  {
    id: 'ba-4',
    name: 'Doppel Munich',
    category: 'boissons-alcoolisees',
    price: '2 000 FCFA',
    description: 'Bière brune de caractère aux arômes intenses de malt torréfié (50cl).',
  },
  {
    id: 'ba-5',
    name: 'Heineken',
    category: 'boissons-alcoolisees',
    price: '2 500 FCFA',
    description: 'Bière blonde internationale de référence (33cl).',
  },
  {
    id: 'ba-6',
    name: 'Guinness Extra Stout',
    category: 'boissons-alcoolisees',
    price: '2 500 FCFA',
    description: 'Stout noir irlandais robuste aux notes de café et cacao amer.',
  },
  {
    id: 'ba-7',
    name: 'Corona Extra',
    category: 'boissons-alcoolisees',
    price: '3 000 FCFA',
    description: 'Bière blonde mexicaine légère servie avec son quartier de citron vert frais dans le goulot.',
  },
  {
    id: 'ba-8',
    name: 'Desperados',
    category: 'boissons-alcoolisees',
    price: '3 000 FCFA',
    description: 'Bière blonde aromatisée à la tequila et zestes d’agrumes.',
  },
  {
    id: 'ba-9',
    name: 'Ricard / Pastis 51',
    category: 'boissons-alcoolisees',
    price: '3 000 FCFA',
    description: 'Grand classique anisé de Marseille servi avec glaçons et carafe d’eau fraîche.',
  },
  {
    id: 'ba-10',
    name: 'Martini Blanc / Rouge',
    category: 'boissons-alcoolisees',
    price: '3 500 FCFA',
    description: 'Vermouth italien servi sur lit de glace avec zeste de citron ou olive.',
  },
  {
    id: 'ba-11',
    name: 'Campari Bitter',
    category: 'boissons-alcoolisees',
    price: '3 500 FCFA',
    description: 'Amer italien rouge aux herbes aromatiques, servi sec ou avec trait d’eau gazeuse.',
  },
  {
    id: 'ba-12',
    name: 'Mojito Classique',
    category: 'boissons-alcoolisees',
    price: '5 500 FCFA',
    description: 'Rhum blanc agricole, menthe fraîche pilée, jus de citron vert pressé, cassonade, eau gazeuse et bitter.',
    tag: 'Cocktail Star',
    isSpecialty: true,
  },
  {
    id: 'ba-13',
    name: 'Piña Colada',
    category: 'boissons-alcoolisees',
    price: '6 000 FCFA',
    description: 'Rhum blanc, rhum brun, crème de coco veloutée et jus d’ananas frais pressé mixés à la glace pilée.',
  },
  {
    id: 'ba-14',
    name: 'Caïpirinha',
    category: 'boissons-alcoolisees',
    price: '5 500 FCFA',
    description: 'Véritable cachaça brésilienne, quartiers de citrons verts écrasés et sucre de canne.',
  },
  {
    id: 'ba-15',
    name: 'Margarita',
    category: 'boissons-alcoolisees',
    price: '6 000 FCFA',
    description: 'Tequila 100% agave, triple sec Cointreau, jus de citron vert frais et givrage au sel fin.',
  },
  {
    id: 'ba-16',
    name: 'Long Island Iced Tea',
    category: 'boissons-alcoolisees',
    price: '7 000 FCFA',
    description: 'Mélange puissant de vodka, gin, rhum blanc, tequila et triple sec avec jus de citron et cola.',
    tag: 'Cocktail Fort',
  },
  {
    id: 'ba-17',
    name: 'Times Signature Cocktail',
    category: 'boissons-alcoolisees',
    price: '7 500 FCFA',
    description: 'Création exclusive de notre chef barman : rhum ambré vieilli, liqueur de fruits de la passion, jus d’ananas rôti et bitter fumé.',
    tag: 'Signature Bar',
    isSpecialty: true,
  },
  {
    id: 'ba-18',
    name: 'Verre de vin (Rouge, Blanc ou Rosé)',
    category: 'boissons-alcoolisees',
    price: '3 500 FCFA',
    description: 'Sélection soignée de notre sommelier au verre parmi les domaines français réputés.',
  },
  {
    id: 'ba-19',
    name: 'Bouteille de vin Rouge sélection AOP',
    category: 'boissons-alcoolisees',
    price: '18 000 FCFA',
    description: 'Bouteille 75cl sélectionnée (Bordeaux AOP ou Côtes-du-Rhône) aux arômes de fruits rouges mûrs et tanins fins.',
  },
  {
    id: 'ba-20',
    name: 'Bouteille de vin Blanc sec',
    category: 'boissons-alcoolisees',
    price: '18 000 FCFA',
    description: 'Bouteille 75cl Sauvignon ou Chardonnay, vif, minéral et fruité, parfait avec nos poissons et fruits de mer.',
  },
  {
    id: 'ba-21',
    name: 'Bouteille de vin Rosé de Provence',
    category: 'boissons-alcoolisees',
    price: '20 000 FCFA',
    description: 'Bouteille 75cl AOP Côtes de Provence, robe pâle, notes d’agrumes et fraîcheur élégante.',
  },
  {
    id: 'ba-22',
    name: 'Bouteille Moët & Chandon Brut Impérial',
    category: 'boissons-alcoolisees',
    price: '75 000 FCFA',
    description: 'Champagne de prestige mondial, bulles fines et vives, arômes de fruits blancs et brioche dorée.',
    tag: 'Champagne d’Exception',
    isSpecialty: true,
  },
  {
    id: 'ba-23',
    name: 'Bouteille Veuve Clicquot Ponsardin',
    category: 'boissons-alcoolisees',
    price: '85 000 FCFA',
    description: 'Champagne brut carte jaune, puissance et élégance aromatique reconnue.',
    tag: 'Prestige',
  },
  {
    id: 'ba-24',
    name: 'Jack Daniel’s Old No. 7 (verre)',
    category: 'boissons-alcoolisees',
    price: '5 000 FCFA',
    description: 'Tennessee whiskey américain filtré goutte à goutte sur charbon de bois d’érable.',
  },
  {
    id: 'ba-25',
    name: 'Johnnie Walker Black Label (verre)',
    category: 'boissons-alcoolisees',
    price: '6 000 FCFA',
    description: 'Blended scotch whisky 12 ans d’âge aux notes riches, douces et fumées.',
  },
  {
    id: 'ba-26',
    name: 'Chivas Regal 12 ans (verre)',
    category: 'boissons-alcoolisees',
    price: '6 000 FCFA',
    description: 'Scotch whisky velouté aux notes de miel sauvage, vanille et noisette.',
  },
  {
    id: 'ba-27',
    name: 'Jameson Irish Whiskey (verre)',
    category: 'boissons-alcoolisees',
    price: '5 000 FCFA',
    description: 'Whiskey irlandais triple distillation d’une remarquable rondeur.',
  },
  {
    id: 'ba-28',
    name: 'Bouteille Jack Daniel’s',
    category: 'boissons-alcoolisees',
    price: '45 000 FCFA',
    description: 'Bouteille 70cl servie avec glaçons et accompagnements de sodas au choix.',
  },
  {
    id: 'ba-29',
    name: 'Bouteille Johnnie Walker Black Label',
    category: 'boissons-alcoolisees',
    price: '55 000 FCFA',
    description: 'Bouteille 70cl servie avec seau à glace et sodas.',
  },
  {
    id: 'ba-30',
    name: 'Baileys Original Irish Cream (verre)',
    category: 'boissons-alcoolisees',
    price: '4 500 FCFA',
    description: 'Onctueuse crème de whisky irlandais servie bien fraîche sur glace.',
  },
  {
    id: 'ba-31',
    name: 'Jägermeister (verre / shot)',
    category: 'boissons-alcoolisees',
    price: '4 500 FCFA',
    description: 'Liqueur allemande aux 56 herbes servie glacée en shot givré.',
  },
  {
    id: 'ba-32',
    name: 'Cognac Hennessy VS (verre)',
    category: 'boissons-alcoolisees',
    price: '7 000 FCFA',
    description: 'Cognac d’exception aux notes boisées, d’épices douces et de fruits secs.',
    tag: 'Prestige',
  },
  {
    id: 'ba-33',
    name: 'Cognac Rémy Martin VSOP (verre)',
    category: 'boissons-alcoolisees',
    price: '8 500 FCFA',
    description: 'Cognac Fine Champagne équilibré aux arômes de vanille et d’abricot mûr.',
  },
  {
    id: 'ba-34',
    name: 'Get 27 (verre)',
    category: 'boissons-alcoolisees',
    price: '4 000 FCFA',
    description: 'Liqueur de menthe poivrée intense servie sur lit de glace pilée.',
  },
];
